import logging

TIME_OUT = 5   # REQUEST TIME OUT, IN SECONDS
RETRY_NUM = 3  # REQUEST RETRY TIME IF FAIL
MAX_NUM_THREADS = 8
LOOP_INTERVAL = 2 # NUMBER OF LOOP PER SECOND
TIME_OUT_PROCESS = 2
CLIENT_ORDER_PREFIX = 'meld_'
DEFAULT_MAX_PROCESSES = 8
LOG_LEVEL = logging.DEBUG
DEBUG_MODE_ENABLED = False
DATA_MAX_LENGTH = 5000
BUFFER_ORDER_QUANTITY = 1.01
